# Generated by Django 6.0.3 on 2026-03-16 07:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation_Cash_Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('BUY', 'Purchase'), ('SELL', 'Liquidation'), ('FEE', 'Commission'), ('INIT', 'Initial Deposit')], max_length=10)),
                ('before_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('after_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('request_id', models.CharField(max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='simulation',
            name='available_cash',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='simulation',
            name='mode',
            field=models.CharField(choices=[('LIVE', 'Live Simulation'), ('BACKTEST', 'Backtest')], default='LIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='simulation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='current_nav',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='initial_cash',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='simulation_holding',
            name='avg_cost',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='simulation_nav_history',
            name='cash',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='simulation_nav_history',
            name='market_value',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='simulation_nav_history',
            name='nav',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='simulation_transaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='simulation_transaction',
            name='type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('100000.0000'), max_digits=20),
        ),
        migrations.AddIndex(
            model_name='dailyprice',
            index=models.Index(fields=['symbol', '-trade_date'], name='stock_daily_symbol__8fcf76_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyprice',
            index=models.Index(fields=['trade_date'], name='stock_daily_trade_d_f5788a_idx'),
        ),
        migrations.AddIndex(
            model_name='simulation_holding',
            index=models.Index(fields=['sim', 'symbol'], name='stock_simul_sim_id_d62cb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='simulation',
            constraint=models.CheckConstraint(condition=models.Q(('available_cash__gte', 0)), name='simulation_cash_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='simulation_holding',
            constraint=models.UniqueConstraint(fields=('sim', 'symbol'), name='unique_holding_per_sim'),
        ),
        migrations.AddField(
            model_name='simulation_cash_flow',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='stock.simulation'),
        ),
        migrations.AddField(
            model_name='simulation_cash_flow',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.simulation_transaction'),
        ),
    ]
