# Generated by Django 6.0.3 on 2026-03-16 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_simulation_cash_flow_simulation_available_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='current_virtual_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
