# Generated by Django 6.0.3 on 2026-03-16 12:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_simulation_current_virtual_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSimulationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_global_date', models.DateField(default=django.utils.timezone.now)),
                ('is_market_open', models.BooleanField(default=True)),
                ('last_step_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Simulation State',
                'verbose_name_plural': 'Global Simulation State',
            },
        ),
        migrations.CreateModel(
            name='TradeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('filled_quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Filled'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('order_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='simulation',
            name='simulation_cash_non_negative',
        ),
        migrations.AlterField(
            model_name='simulation',
            name='mode',
            field=models.CharField(choices=[('LIVE', 'Live Multiplayer'), ('BACKTEST', 'Private Backtest')], default='LIVE', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='simulation',
            constraint=models.CheckConstraint(condition=models.Q(('available_cash__gte', 0)), name='simulation_cash_non_negative_v2'),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stock.simulation'),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.company'),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulation_transaction',
            name='matched_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.tradeorder'),
        ),
        migrations.AddIndex(
            model_name='tradeorder',
            index=models.Index(fields=['symbol', 'status', 'side', 'price'], name='stock_trade_symbol__6e587d_idx'),
        ),
    ]
