# Generated by Django 6.0.3 on 2026-03-17 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_globalsimulationstate_tradeorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_transaction',
            name='opponent_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterpart_transactions', to='stock.tradeorder'),
        ),
    ]
