# Generated by Django 6.0.3 on 2026-03-24 03:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_tradeorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_transaction',
            name='fees',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
    ]
