# Generated by Django 6.0.3 on 2026-04-08 04:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_simulation_transaction_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='current_nav',
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='frozen_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='opponent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_as_opponent', to='stock.tradeorder'),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='remaining_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tradeorder',
            name='avg_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='tradeorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Filled'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10),
        ),
        migrations.AddIndex(
            model_name='tradeorder',
            index=models.Index(fields=['status', 'symbol'], name='stock_trade_status_1fa70b_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeorder',
            index=models.Index(fields=['created_at'], name='stock_trade_created_e49ed1_idx'),
        ),
    ]
