# Generated by Django 6.0.3 on 2026-04-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_remove_simulation_current_nav_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tradeorder',
            name='stock_trade_status_1fa70b_idx',
        ),
        migrations.RemoveIndex(
            model_name='tradeorder',
            name='stock_trade_created_e49ed1_idx',
        ),
        migrations.AlterField(
            model_name='tradeorder',
            name='avg_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='tradeorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Filled'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='FILLED', max_length=10),
        ),
        migrations.RemoveField(
            model_name='tradeorder',
            name='frozen_amount',
        ),
        migrations.RemoveField(
            model_name='tradeorder',
            name='matched_at',
        ),
        migrations.RemoveField(
            model_name='tradeorder',
            name='opponent_order',
        ),
        migrations.RemoveField(
            model_name='tradeorder',
            name='remaining_quantity',
        ),
    ]
