# Generated by Django 6.0.3 on 2026-04-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_simulation_transaction_digital_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation_transaction',
            name='voucher_no',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='凭证编号'),
        ),
    ]
