# Generated by Django 6.0.4 on 2026-05-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_alter_simulation_transaction_voucher_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='investment_style',
            field=models.CharField(choices=[('CONSERVATIVE', '保守型'), ('MODERATE', '稳健型'), ('AGGRESSIVE', '激进型')], default='MODERATE', max_length=20, verbose_name='投资风格'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='name',
            field=models.CharField(default='我的投资组合', max_length=100),
        ),
    ]
