# Generated by Django 6.0.3 on 2026-07-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_simulation_investment_style_alter_simulation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('trader', '普通交易员')], default='trader', max_length=10, verbose_name='用户角色'),
        ),
    ]
