# Generated by Django 6.0.3 on 2026-07-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
    ]
