# Generated by Django 6.0.3 on 2026-03-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_simulation_transaction_opponent_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_transaction',
            name='realized_pnl',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
