# Generated by Django 6.0.3 on 2026-03-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_simulation_transaction_realized_pnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorder',
            name='avg_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=18, null=True),
        ),
    ]
