# Generated by Django 6.0.3 on 2026-03-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_industry_financials_current_assets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Filled'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='FILLED', max_length=10),
        ),
    ]
