# Generated by Django 6.0.3 on 2026-04-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_remove_tradeorder_stock_trade_status_1fa70b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_transaction',
            name='digital_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='simulation_transaction',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='凭证编号'),
        ),
    ]
